### ISSUE TITLE
Using Bootstrap 4

### ISSUE THREAD

**Issue by lendra85** [wdmg/bootstrap-wysiwyg#2]
Hi,

I am using Bootstrap 4, but it showed double `textarea` here. what should i do to fix it?

Thanks

Sailendra

**Comment by alex-wdmg** [comment]
Hi, Sailendra! The plugin does not create or duplicate the current <textarea /> input, but only uses the existing one at initiation as a parent container. You can temporarily disable the plugin and look at the DOM to find out what exactly is creating the take.
